name: Commands

on:
  workflow_dispatch:

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
    - run: |
        deprecated=true
        if [[ deprecated ]]; then
          echo "::warning::Deprecated function found"
        fi
