name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-one: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first Github actions workflow!"
