name: Manual Trigger
on:
  workflow_dispatch: # This is the trigger that responsible for
                     # running actions from GUI or Github CLI
    inputs:
      environment:
        description: "Choose environmnet"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying the application..."
