on:
  schedule:
    - cron: "0 0 * * *" # It runs daily at 00:00 UTC

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
        - name: Print message
          run: echo "Running the scheduled task"
